import type { SectionDifficulty } from './types';

// Fase 6: inside tricks.
// Regla de la propuesta inicial (ajustable):
// 1. Base por rotacion: 360 -> 2, 540/720 -> 3, 900/1080 -> 4, 1260/1440/1620 -> 5.
// 2. Para trucos sin grados, base por el giro o mortal: raiz, inside flip, cheat,
//    aerial, side flip, tuck y layout -> 2; full, gainer y hook -> 3; double full o
//    doble giro -> 5; triple o mas -> 5. Los trucos base de twist (butterfly twist,
//    aerial twist) y el butterfly kick parten de 2 o 3 segun su familia.
// 3. +1 si la variante es compuesta (knife, double, gyro, hyper, turbo, shuriken,
//    feilong, crowd awakener, sidekick, rodeo, paraknife, wackknife, hawkeye, twist,
//    doubleleg, round, switch), con tope 5.
// Cubre los 123 trucos de la seccion inside de Loopkicks, curados sobre los ids
// reales de TrickingAPI.
export const inside: SectionDifficulty = {
  aerial: 2,
  aerialHelicoptero: 3,
  aerialHook: 3,
  aerialMega: 3,
  aerialScissor: 3,
  aerialSidewinder: 3,
  aerialTwist: 3,
  aerialTwistDoubleleg: 4,
  aerialTwistGumbi: 4,
  aerialTwistGumbiHelicoptero: 5,
  blasterscoot: 3,
  butterflyKick: 2,
  butterflyKickHelicoptero: 3,
  butterflyKickHelicopteroRound: 4,
  butterflyKickLateHook: 3,
  butterflyKickScissor: 3,
  butterflyKickSwitch: 3,
  butterflyKickSwitchHyperhook: 5,
  butterflyKickTeradaGrab: 3,
  butterflyTwist: 3,
  butterflyTwistAxe: 4,
  butterflyTwistDoubleleg: 4,
  butterflyTwistDoublelegTwist: 5,
  butterflyTwistDoubleRound: 5,
  butterflyTwistFeilongSwipe: 4,
  butterflyTwistHawkeye: 4,
  butterflyTwistHyper: 4,
  butterflyTwistHyperhook: 4,
  butterflyTwistIn: 4,
  butterflyTwistKnife: 4,
  butterflyTwistRound: 4,
  butterflyTwistRoundLateRound: 5,
  butterflyTwistShurikane: 4,
  butterflyTwistShuriken: 4,
  butterflyTwistShurikenHyperhook: 5,
  butterflyTwistShurikenTwist: 5,
  butterflyTwistSnapu: 4,
  butterflyTwistSwipe: 4,
  butterflyTwistTwistKick: 4,
  butterflyTwistWackknife: 4,
  butterKnife: 3,
  cartwheel: 2,
  cartwheelLateSwipe: 3,
  cartwheelTwist: 3,
  doubleAerialTwist: 5,
  doubleButterflyTwist: 5,
  doubleButterflyTwistHyper: 5,
  doubleButterflyTwistRound: 5,
  doubleButterflyTwistSnapu: 5,
  doublePeterPanButterflyTwist: 5,
  grandMasterArabian: 4,
  grandMasterRocketboi: 4,
  grandMasterScissor: 3,
  grandMasterScoot: 3,
  grandMasterSwipe: 3,
  grandMasterSwipeknife: 4,
  grandMasterTwist: 4,
  grandMasterTwistDoubleleg: 5,
  helicoptero: 3,
  helicopteroEKick: 3,
  illusionTwist: 4,
  inward360DiveRoll: 3,
  kaydem: 3,
  macaron: 3,
  masterscoot: 3,
  masterscootTwist: 4,
  masterswipe: 3,
  masterswipeHelicoptero: 3,
  oneElbowCartwheelTwist: 4,
  oneHandedCartwheel: 2,
  oneHandedCartwheelTwist: 4,
  palmkick: 2,
  palmkickKyro: 3,
  palmkickScissorSwipe: 3,
  rodeoGrandMasterSwipe: 4,
  roundoff: 2,
  scoot: 2,
  scootHyper: 3,
  scootTwist: 3,
  sidewinder: 3,
  sketchdownRaiz: 3,
  takDoubleFull: 5,
  takDoubleFullHyper: 5,
  takDoubleFullHyperhook: 5,
  takDoubleFullRound: 5,
  takDoubleFullTouchdown: 5,
  takFull: 3,
  takFullHyperhook: 4,
  takFullKyro: 4,
  takFullPizzaboy: 4,
  takFullRound: 4,
  takFullShurikenHyperhook: 5,
  takFullSwipe: 4,
  takFullWackknife: 4,
  takRodeoFull: 4,
  takTripleFull: 5,
  takuraba: 3,
  takurabaScissor: 3,
  touchdownAerialTwist: 3,
  touchdownButterflyTwist: 4,
  touchdownTakFull: 3,
  touchdownWrapFull: 3,
  touchupDoubleButterflyTwist: 5,
  tripleAerialTwist: 5,
  tripleButterflyTwist: 5,
  wrapArabian: 4,
  wrapArabianScissor: 4,
  wrapDoubleFull: 5,
  wrapDoubleFullMega: 5,
  wrapDoubleFullSnapu: 5,
  wrapFull: 3,
  wrapFullDoubleleg: 4,
  wrapFullHyper: 4,
  wrapFullHyperhook: 4,
  wrapFullLateRound: 4,
  wrapFullPike: 4,
  wrapFullRound: 4,
  wrapFullShurikane: 4,
  wrapFullShurikenHyperhook: 5,
  wrapFullSnapu: 4,
  wrapFullSwipe: 4,
  wrapFullSwipeknife: 4,
  wrapTripleFull: 5,
};
