import type { SectionDifficulty } from './types';

// Fase 7: outside tricks. Los 73 trucos de la seccion outside de Loopkicks, curados a
// mano sobre los ids reales de TrickingAPI (ajustable por el usuario).
// Criterio aplicado:
// 1. Base por rotacion: 720 -> 3, 900/1080 -> 4, 1260 o mas -> 5.
// 2. Trucos sin grados: base 2 (raiz, raiz-in, side flip, sideswipe, spyder, gumbi,
//    scrubba, doubleleg, machine, e-kick, cali roll, touchdown) o base 3 (envergado,
//    reversao, snapu, swipeknife, crackknife y las familias lotus, sailor, feilong).
// 3. Cada modificador compuesto presente suma 1 y se apila (twist, hyperhook, round,
//    late, swipe, snapu, reversao, x-out, roll, wackknife, shuriken, crowd awakener,
//    rodeo, sidekick, hawkeye, turbo, broken), con tope 5. "double" sobre un truco ya
//    compuesto lleva directo a 5.
export const outside: SectionDifficulty = {
  brokenScrubba: 3,
  caliRoll: 2,
  cheat720Twist: 3,
  cheat720TwistBroken: 4,
  cheat720TwistHyperhook: 4,
  cheat720TwistRound: 4,
  crackknife: 3,
  doubleDoubleleg: 5,
  doubleSideflip: 5,
  doubleleg: 2,
  doublelegDoubleTwist: 5,
  doublelegRodeo: 3,
  doublelegSidekick: 3,
  doublelegTwist: 3,
  doublelegTwistRound: 4,
  doublelegXOut: 3,
  doublelegXOutHyperhook: 4,
  eKick: 2,
  envergado: 3,
  envergadoDoubleTwist: 5,
  envergadoTwist: 4,
  feilongSnapu: 3,
  gumbi: 2,
  lotusCrowdAwakener: 3,
  lotusDoubleleg: 3,
  lotusDoublelegHyperhook: 4,
  lotusLateRound: 3,
  lotusRodeo: 3,
  lotusShuriken: 3,
  machine: 2,
  popSnapu: 3,
  popSwipeknife: 3,
  popTaiFighter: 3,
  raiz: 2,
  raizHyperhook: 3,
  raizHyperhookTurbo: 4,
  raizReversao: 3,
  raizShurikane: 3,
  raizIn: 2,
  reversao: 3,
  rodeoSnapu: 3,
  sailorGumbi: 3,
  sailorMoon: 3,
  sailorMoonDoubleleg: 4,
  sailorMoonDoublelegTwist: 5,
  sailorMoonHawkeye: 4,
  sailorMoonHyperhook: 4,
  sailorMoonLateRound: 4,
  sailorMoonReversao: 4,
  sailorMoonRound: 4,
  sailorMoonSnapu: 4,
  sailorMoonTwist: 4,
  sailorMoonWackknife: 4,
  scrubba: 2,
  sideflip: 2,
  sideflipRound: 3,
  sideswipe: 2,
  sideswipeLateRound: 3,
  sideswipeLateSwipe: 3,
  snapu: 3,
  snapuDoubleleg: 4,
  snapuHyperhook: 4,
  snapuRound: 4,
  snapuTwist: 4,
  spyder: 2,
  spyderTwist: 3,
  spyderTwistRound: 4,
  swipeknife: 3,
  swipeknifeTurbo: 4,
  touchdownRaiz: 2,
  touchdownRaizRoll: 3,
  touchdownRaizTwist: 3,
  touchdownSwipe: 3,
};
